//
// Another CPU Language - ACPUL - a{};
//
// THIS SOFTWARE IS PROVIDED BY THE FREEBSD PROJECT ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
// SHALL THE FREEBSD PROJECT OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
// WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY
// OF SUCH DAMAGE.
//
// Made by d08ble, thanks for watching.
//

#ifndef ACPULanguage_ErrorNumbers_h
#define ACPULanguage_ErrorNumbers_h

namespace acpul {

    enum ErrorNumbers
    {
        // SYNTAX
        EN_SYNTAX_ERR   = 10,
        EN_SYNTAX_WARN,
        
        // DATA
        EN_DATA_ERR     = 20,
        
        // PROC
        EN_PROC_ERR     = 30,
        
        // COMPILE
        EN_COMPILE_ERR  = 40,
        
        // EXE
        EN_EXE_ERR      = 50,
        EN_EXE_INFO,

        // OBJ
        EN_OBJ_ERR      = 60,
        
        // CORE
        EN_CORE_ERR     = 70,
        
        // CODE BLOCK
        EN_CODE_BLOCK_ERR = 80,
    };
    
}

#endif
